### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Roboxkin** [GRudinsky/image-reader#3]
If you run it as you wrote “npm build” in the instructions, it won’t work. After googling a little, I realized that the correct way would be “npm run build”, well, okay, I sort of figured it out. Now when I run "npm start", I get "Server is running at http://localhost:undefined"

**Comment by Roboxkin** [comment]
I will add an answer for users in the future.
If anyone has the same problem with the port, then open the file "package.json" and change "start": "node dist/src/index.js" to "start": "set PORT=5000 && node dist/src/index .js".
Then feel free to run "npm start" and localhost:5000 will work

**Comment by GRudinsky** [comment]
> I will add an answer for users in the future. If anyone has the same problem with the port, then open the file "package.json" and change "start": "node dist/src/index.js" to "start": "set PORT=5000 && node dist/src/index .js". Then feel free to run "npm start" and localhost:5000 will work

Thank you @Roboxkin  for raising this. I forgot to include the initial instruction to create the .env file with PORT key-value pair in the file contents but I also appreciate your solution which I will add in my next commit. Feel free to also raise a fix PR in case you want to contribute.

**Comment by GRudinsky** [comment]
This has now been solved in [this commit.](https://github.com/GRudinsky/image-reader/commit/1b8ccbfa9d57c0172451734d975323f1cb363e97) Closing.
